CURRENT_VERSION = "v1.0.0"

LANG_MAP = {
    "en": {
        # --- Common / Window ---
        "home": "Home",
        "settings": "Settings",
        "about": "About",
        "toolbox": "Toolbox",
        "open_navigation": "Open Navigation",
        "cancel": "Cancel",
        "delete": "Delete",
        "confirm_overwrite": "Overwrite",
        "file_not_found": "Local file not found",
        "network_error": "Network request error",
        "tray_show": "Show EmuMan",
        "tray_launch_master": "Launch Master",
        "tray_launch_nightly": "Launch Nightly",
        "tray_open_dir": "Open Directory",
        "tray_open_eden_dir": "Eden Emulator Dir",
        "tray_open_user_dir": "Eden Settings Dir",
        "tray_open_firmware_dir": "Firmware Save Dir",
        "tray_open_backup_dir": "Backup Save Dir",
        "tray_exit": "Exit",
        "error": "Error",
        "warning": "Warning",
        "success": "Success",
        "done": "Done",
        "ok": "OK",
        "close": "Close",
        "loading": "Loading...",
        "online": "Online",
        "not_found": "Not Found",

        
        # --- Home Interface ---
        "status_none": "Status: Not Found",
        "status_ready": "Status: Eden Ready",
        "status_prefix": "Current: ",
        "status_unknown": "Unknown",
        "status_not_installed": "Not Installed",
        "eden_path": "Eden Path",
        "browse": "Browse",
        "stable_tag": "Stable",
        "dev_tag": "Dev",
        "changelog_placeholder": "Select a version to view changelogs...",
        "master_channel": "Mainline Channel",
        "nightly_channel": "Nightly Channel",
        "launch": "Launch",
        "download_btn": "Download",
        "select_download": "Multiple builds detected, please confirm download:",
        "no_platform_build": "No builds available for your platform in this release",
        "sync_data": "Syncing latest version info...",
        "sync_data_success": "Versions synced successfully!",
        "sync_data_latest": "Version list is up to date",
        "refresh_data": "Refresh Version List",
        
        "download_preparing": "Preparing download",
        "downloading": "Downloading",
        "download_cancelled": "Download Cancelled",
        "download_success": "Emulator ready",
        "download_failed": "Download failed",
        "extract_manual": "Manual extraction required",
        "extract_manual_msg": ".7z file requires manual extraction, will be saved as",
        "launch_error": "Launch error",
        "launch_failed": "Launch failed",
        "config_missing": "Configuration Missing",
        "config_missing_msg": "Eden Emulator path is not configured. Please set it before downloading.\nSet it now?",
        "path_exists": "File Exists",
        "path_exists_msg": "Target directory already exists. Overwrite?\n\nNote: This will delete the old version.",
        "update_app_title": "Software Update",
        "update_app_msg": "New version detected. Update and restart now?\n\nNote: The application will be automatically replaced and restarted.",
        
        # --- Firmware ---
        "firmware_version": "Eden Firmware: {}",
        "firmware_not_detected": "Firmware not detected",
        "firmware_update_available": "Firmware update available: {}",
        "firmware_install_title": "Install Firmware",
        "firmware_install_confirm": "Download and install firmware {}?\n\nThis will replace existing firmware files.",
        "firmware_update_hint": " (Update: {})",
        "firmware_install_confirm_local": "Install firmware {}?\n\nThis will replace existing firmware files.",
        "firmware_already_installed": "Version {} is already installed.\nAre you sure you want to reinstall?",
        "firmware_downloading": "Downloading Firmware...",
        "firmware_verifying": "Verifying Integrity...",
        "firmware_installing": "Installing Firmware...",
        "firmware_install_success": "Success",
        "firmware_install_failed": "Failed",
        "firmware_install_please_wait": "Please wait...",
        "firmware_restart_title": "Restart Required",
        "firmware_restart_msg": "Firmware installed successfully.\n\nStart Eden now to verify installation?",
        "start_eden": "Start Eden",
        "later": "Later",
        "please_launch_eden": "Please launch Eden to complete verification.",
        "cancelling": "Cancelling...",
        
        # --- Settings ---
        "settings_group_app": "Application Settings",
        "check_update_start": "Check Update on Start",
        "minimize_to_tray": "Minimize to Tray on Close",
        "remember_last_selection": "Remember Last Version Selection",
        "settings_group_download": "Download Management",
        "settings_group_path": "Path Management",
        "theme_mode": "Application Theme",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "theme_auto": "System",
        "lang": "Language",
        "downloader_engine": "Download Engine",
        "fetch_limit": "Fetch Limit",
        "keep_archive": "Keep Eden Archive",
        "disable_ipv6": "Disable IPv6 (Aria2)",
        "aria2_verbose_log": "Verbose Log (Aria2)",
        "backup_path": "Backup Path",
        "firmware_path": "Firmware Path",
        "keep_firmware_archive": "Keep Firmware Archive",
        "verify_firmware_checksum": "Verify Firmware (SHA256)",
        "dl_auto": "Auto (Aria2 Preferred)",
        "dl_requests": "Internal (Requests)",
        "open_user_folder": "Open Eden Data Folder",
        "open_eden_folder": "Open Eden Emulator Folder",
        "user_folder_not_found": "Eden Data Folder Not Found",
        
        # --- About ---
        "project_desc": "EmuMan is an open-source multi-version manager for Eden Emulator, facilitating easy switching and performance testing across versions, alongside streamlined installation and updates.",
        "view_on_github": "Source Code",
        "report_issue": "Report Issue",
        "credits": "Credits",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        
        # --- Toolbox ---
        "firmware_manager": "Firmware Manager",
        "firmware_manager_desc": "Manage local firmware, install manually, and check for updates.",
        "firmware_local_versions": "Local Firmware: {}",
        "firmware_check_update": "Check Update",
        "firmware_install_local": "Install",
        "firmware_no_local": "No Local Firmware",
        "firmware_select_file": "Select Firmware File",
        "open_firmware_folder": "Open Firmware Folder",
        "save_manager": "Save Manager",
        "save_manager_desc": "Backup and restore your game saves safely.",
        "save_backup": "New Backup",
        "save_restore": "Restore",
        "backup_success": "Backup Created Successfully",
        "backup_saved_title": "Backup Successful",
        "backup_saved_msg": "Backup saved to:\n{}",
        "restore_confirm": "Are you sure you want to restore this backup?\nCurrent saves will be overwritten permanently!",
        "restore_success": "Save Data Restored Successfully",
        "delete_confirm": "Are you sure you want to delete this backup?",
        "delete_confirm_title": "Confirm Delete",
        "open_backup_folder": "Open Backup Folder",
        "last_backup": "Last Backup: {}",
        "last_backup_none": "Last Backup: Never",
        "col_date": "Date",
        "col_name": "Name",
        "col_version": "Version",
        "col_status": "Status",
        "col_size": "Size",
        "tag_local": "Local",
        "tag_remote": "Remote",
        "tag_installed": "Installed",
        "no_backups_found": "No Backups Found",
        "backup_failed": "Backup Failed",
        "restore_failed": "Restore Failed",
        "mod_installed_count": "Installed Mods: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "Imported {} files",

        
        # --- Keys Manager ---
        "keys_manager": "Keys Manager",
        "keys_manager_desc": "Manage emulator decryption keys (prod.keys/title.keys)",
        "keys_status_found": "Installed",
        "keys_status_missing": "Missing",
        "import_keys": "Import Keys",
        "auto_scan_keys": "Auto Scan",
        "open_keys_folder": "Open Keys Folder",
        "keys_imported": "Keys Imported Successfully",
        "keys_import_failed": "Import Failed",
        "scan_result": "Found {} key files. Import all?",
        "no_keys_found": "No keys found in common paths",
        
        # --- Mod Manager ---
        "mod_manager": "Mod Manager",
        "mod_manager_desc": "Manage installed Mods (LayeredFS)",
        "open_mod_folder": "Open Mod Folder",
        "no_mods_found": "No Mods Found",
        "mod_enabled": "Enabled",
        "mod_disabled": "Disabled",
        # Log Manager
        "log_manager": "Log Manager",
        "log_manager_desc": "Manage Eden Emulator logs, export them for reporting issues.",
        "export_logs": "Export Logs",
        "open_log_dir": "Open Log Folder",
        "log_export_success": "Logs exported successfully to:\n{}",
        "log_export_fail": "Failed to export logs:\n{}",
        "toggle_mod": "Toggle",

        "on": "On",
        "off": "Off",
        "no_build": "No Build",
        "log_folder_empty": "Log folder is empty.",
        "create_folder_fail": "Could not create folder: {}",
        "exe_not_found": "Executable not found: {}",
        "create_dir_fail": "Failed to create directory: {}\n{}",
    },
    "zh": {
        # --- Common / Window ---
        "home": "首页",
        "settings": "设置",
        "about": "关于",
        "toolbox": "工具箱",
        "open_navigation": "打开导航",
        "cancel": "取消",
        "delete": "删除",
        "confirm_overwrite": "覆盖安装",
        "file_not_found": "找不到本地文件",
        "network_error": "网络请求错误",
        "tray_show": "显示 EmuMan",
        "tray_launch_master": "启动 Eden Master",
        "tray_launch_nightly": "启动 Eden Nightly",
        "tray_open_dir": "打开目录",
        "tray_open_eden_dir": "Eden 模拟器目录",
        "tray_open_user_dir": "Eden 设置目录",
        "tray_open_firmware_dir": "固件保存目录",
        "tray_open_backup_dir": "存档备份目录",
        "tray_exit": "退出",
        "error": "错误",
        "warning": "警告",
        "success": "成功",
        "done": "完成",
        "ok": "确定",
        "close": "关闭",
        "loading": "加载中...",
        "online": "在线",
        "not_found": "未找到",

        
        # --- Home Interface ---
        "status_none": "状态：未检测到模拟器",
        "status_ready": "状态: Eden 已就绪",
        "status_prefix": "当前版本: ",
        "status_unknown": "未知",
        "status_not_installed": "未安装",
        "eden_path": "Eden 模拟器路径",
        "browse": "选择文件夹",
        "stable_tag": "稳定版",
        "dev_tag": "开发版",
        "changelog_placeholder": "选择版本查看更新日志...",
        "master_channel": "Master 稳定分支",
        "nightly_channel": "Nightly 开发分支",
        "launch": "启动",
        "download_btn": "下载",
        "select_download": "检测到多个版本，请确认下载文件：",
        "no_platform_build": "此 Release 暂无适用于您平台的构建",
        "sync_data": "正在同步最新版本信息...",
        "sync_data_success": "版本同步成功",
        "sync_data_latest": "版本列表已是最新",
        "refresh_data": "刷新版本列表",
        
        "download_preparing": "正在准备下载",
        "downloading": "正在下载...",
        "download_cancelled": "下载已取消",
        "download_success": "模拟器已就绪",
        "download_failed": "下载失败",
        "extract_manual": "需要手动解压",
        "extract_manual_msg": ".7z 文件需要手动解压，将保存为",
        "launch_error": "启动出错",
        "launch_failed": "启动失败",
        "config_missing": "配置缺失",
        "config_missing_msg": "检测到尚未配置模拟器路径，下载前需要先指定安装位置。\n是否立即设置？",
        "path_exists": "文件已存在",
        "path_exists_msg": "目标目录已存在，是否覆盖？\n\n注意：覆盖将删除旧版本文件。",
        "update_app_title": "软件更新",
        "update_app_msg": "检测到新版本，是否立即自动更新并重启？\n\n注意：新版本将自动下载并替换当前程序。",
        
        # --- Firmware ---
        "firmware_version": "Eden 固件版本: {}",
        "firmware_not_detected": "未检测到固件",
        "firmware_update_available": "固件更新可用: {}",
        "firmware_install_title": "安装固件",
        "firmware_install_confirm": "下载并安装固件 {}?\n\n这将替换现有的固件文件。",
        "firmware_update_hint": " (新版本: {})",
        "firmware_install_confirm_local": "安装固件 {}?\n\n这将替换现有的固件文件。",
        "firmware_already_installed": "版本 {} 已经安装。\n确定要重新安装吗？",
        "firmware_downloading": "正在下载固件...",
        "firmware_verifying": "正在校验完整性...",
        "firmware_installing": "正在安装固件...",
        "firmware_install_success": "固件安装成功",
        "firmware_install_failed": "固件安装失败",
        "firmware_restart_title": "需要重启",
        "firmware_restart_msg": "固件安装成功。\n\n是否立即启动 Eden 以验证安装？",
        "start_eden": "启动 Eden",
        "later": "稍后",
        "please_launch_eden": "请启动 Eden 以完成固件验证。",
        "cancelling": "正在取消...",
        "firmware_install_please_wait": "请稍候...",
        
        # --- Settings ---
        "settings_group_app": "应用设置",
        "check_update_start": "启动时检查应用更新",
        "minimize_to_tray": "关闭时最小化到托盘",
        "remember_last_selection": "记住上次选择的版本",
        "settings_group_download": "下载管理",
        "settings_group_path": "路径管理",
        "theme_mode": "应用主题",
        "theme_light": "浅色",
        "theme_dark": "深色",
        "theme_auto": "跟随系统",
        "lang": "界面语言",
        "downloader_engine": "下载引擎",
        "fetch_limit": "版本显示数量",
        "keep_archive": "保留 Eden 压缩包",
        "disable_ipv6": "禁用 IPv6 (Aria2)",
        "aria2_verbose_log": "详细日志 (Aria2)",
        "backup_path": "存档备份位置",
        "firmware_path": "固件保存位置",
        "keep_firmware_archive": "固件安装后保留压缩包",
        "verify_firmware_checksum": "校验固件完整性 (SHA256)",
        "dl_auto": "自动 (优先 Aria2)",
        "dl_requests": "内部 (Python Requests)",
        "open_user_folder": "打开 Eden 配置文件夹",
        "open_eden_folder": "打开 Eden 模拟器文件夹",
        "user_folder_not_found": "未找到 Eden 配置文件夹",
        
        # --- About ---
        "project_desc": "EmuMan 是一个开源的 Eden 模拟器多版本管理工具，支持便捷切换与测试不同版本的性能表现，并简化安装、更新及固件管理流程。",
        "view_on_github": "查看源码",
        "report_issue": "反馈问题",
        "credits": "Credits",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        
        # --- Toolbox ---
        "firmware_manager": "固件管理",
        "firmware_manager_desc": "管理本地已下载的固件版本，支持手动安装和更新检测。",
        "firmware_local_versions": "本地固件: {}",
        "firmware_check_update": "检查更新",
        "firmware_install_local": "安装",
        "firmware_no_local": "无本地固件",
        "firmware_select_file": "选择固件文件",
        "open_firmware_folder": "打开固件文件夹",
        "save_manager": "存档管理",
        "save_manager_desc": "安全地备份与还原您的游戏存档数据。",
        "save_backup": "新建备份",
        "save_restore": "还原存档",
        "backup_success": "备份创建成功",
        "backup_saved_title": "备份成功",
        "backup_saved_msg": "存档已备份至：\n{}",
        "restore_confirm": "确定要还原此备份吗？\n当前存档将被覆盖且无法找回！",
        "restore_success": "存档还原成功",
        "delete_confirm": "确定要删除此备份文件吗？",
        "delete_confirm_title": "确认删除",
        "open_backup_folder": "打开备份文件夹",
        "last_backup": "上次备份：{}",
        "last_backup_none": "上次备份：无",
        "col_date": "日期",
        "col_name": "文件名",
        "col_version": "版本",
        "col_status": "状态",
        "col_size": "大小",
        "tag_local": "本地",
        "tag_remote": "远程",
        "tag_installed": "已安装",
        "no_backups_found": "未找到备份文件",
        "backup_failed": "备份失败",
        "restore_failed": "还原失败",
        "mod_installed_count": "已安装模组: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "已导入 {} 个文件",

        
        # --- Keys Manager ---
        "keys_manager": "密钥管理",
        "keys_manager_desc": "管理模拟器解密密钥 (prod.keys/title.keys)",
        "keys_status_found": "已安装",
        "keys_status_missing": "缺失",
        "import_keys": "导入密钥",
        "auto_scan_keys": "自动扫描",
        "open_keys_folder": "打开密钥文件夹",
        "keys_imported": "密钥导入成功",
        "keys_import_failed": "导入失败",
        "scan_result": "共找到 {} 个密钥文件，是否全部导入？",
        "no_keys_found": "未在常见路径通过扫描找到密钥",
        
        # --- Mod Manager ---
        "mod_manager": "Mod 管理",
        "mod_manager_desc": "查看与管理已安装的 Mod (LayeredFS)",
        "open_mod_folder": "打开 Mod 文件夹",
        "no_mods_found": "未检测到 Mod",
        "mod_enabled": "已启用",
        "mod_disabled": "已禁用",
        "toggle_mod": "切换开关",
        # Log Manager
        "log_manager": "日志管理",
        "log_manager_desc": "管理 Eden 模拟器日志，可导出日志以便反馈问题。",
        "export_logs": "导出日志",
        "open_log_dir": "打开日志目录",
        "log_export_success": "日志已成功导出到：\n{}",
        "log_export_fail": "导出日志失败：\n{}",

        "on": "开",
        "off": "关",
        "no_build": "未找到构建",
        "log_folder_empty": "日志目录为空。",
        "create_folder_fail": "无法创建文件夹: {}",
        "exe_not_found": "找不到可执行文件: {}",
        "create_dir_fail": "创建目录失败: {}\n{}",
    },
    "cht": {
        "home": "首頁",
        "settings": "設定",
        "about": "關於",
        "toolbox": "工具箱",
        "open_navigation": "打開導航",
        "cancel": "取消",
        "delete": "刪除",
        "confirm_overwrite": "覆蓋安裝",
        "file_not_found": "找不到本地文件",
        "network_error": "網絡請求錯誤",
        "tray_show": "顯示 EmuMan",
        "tray_launch_master": "啟動 Eden Master",
        "tray_launch_nightly": "啟動 Eden Nightly",
        "tray_open_dir": "打開目錄",
        "tray_open_eden_dir": "Eden 模擬器目錄",
        "tray_open_user_dir": "Eden 設定目錄",
        "tray_open_firmware_dir": "固件保存目錄",
        "tray_open_backup_dir": "存檔備份目錄",
        "tray_exit": "退出",
        "error": "錯誤",
        "warning": "警告",
        "success": "成功",
        "done": "完成",
        "ok": "確定",
        "close": "關閉",
        "loading": "加載中...",
        "online": "在線",
        "not_found": "未找到",

        "status_none": "狀態：未檢測到模擬器",
        "status_ready": "狀態: Eden 已就緒",
        "status_prefix": "當前版本: ",
        "status_unknown": "未知",
        "status_not_installed": "未安裝",
        "eden_path": "Eden 模擬器路徑",
        "browse": "選擇文件夾",
        "stable_tag": "穩定版",
        "dev_tag": "開發版",
        "changelog_placeholder": "選擇版本查看更新日誌...",
        "master_channel": "Master 穩定分支",
        "nightly_channel": "Nightly 開發分支",
        "launch": "啟動",
        "download_btn": "下載",
        "select_download": "檢測到多個版本，請確認下載文件：",
        "no_platform_build": "此 Release 暫無適用於您平台的構建",
        "sync_data": "正在同步最新版本信息...",
        "sync_data_success": "版本同步成功",
        "sync_data_latest": "版本列表已是最新",
        "refresh_data": "刷新版本列表",
        "download_preparing": "正在準備下載",
        "downloading": "正在下載...",
        "download_cancelled": "下載已取消",
        "download_success": "模擬器已就緒",
        "download_failed": "下載失敗",
        "extract_manual": "需要手動解壓",
        "extract_manual_msg": ".7z 文件需要手動解壓，將保存為",
        "launch_error": "啟動出錯",
        "launch_failed": "啟動失敗",
        "config_missing": "配置缺失",
        "config_missing_msg": "檢測到尚未配置模擬器路徑，下載前需要先指定安裝位置。\n是否立即設置？",
        "path_exists": "文件已存在",
        "path_exists_msg": "目標目錄已存在，是否覆蓋？\n\n注意：覆蓋將刪除舊版本文件。",
        "update_app_title": "軟件更新",
        "update_app_msg": "檢測到新版本，是否立即自動更新並重啟？\n\n注意：新版本將自動下載並替換當前程序。",
        "firmware_version": "Eden 固件版本: {}",
        "firmware_not_detected": "未檢測到固件",
        "firmware_update_available": "固件更新可用: {}",
        "firmware_install_title": "安裝固件",
        "firmware_install_confirm": "下載並安裝固件 {}?\n\n這將替換現有的固件文件。",
        "firmware_update_hint": " (新版本: {})",
        "firmware_install_confirm_local": "安裝固件 {}?\n\n這將替換現有的固件文件。",
        "firmware_already_installed": "版本 {} 已經安裝。\n確定要重新安裝嗎？",
        "firmware_downloading": "正在下載固件...",
        "firmware_verifying": "正在校驗完整性...",
        "firmware_installing": "正在安裝固件...",
        "firmware_install_success": "固件安裝成功",
        "firmware_install_failed": "固件安裝失敗",
        "firmware_restart_title": "需要重啟",
        "firmware_restart_msg": "固件安裝成功。\n\n是否立即啟動 Eden 以驗證安裝？",
        "start_eden": "啟動 Eden",
        "later": "稍後",
        "please_launch_eden": "請啟動 Eden 以完成固件驗證。",
        "cancelling": "正在取消...",
        "firmware_install_please_wait": "請稍候...",
        "settings_group_app": "應用設定",
        "check_update_start": "啟動時檢查應用更新",
        "minimize_to_tray": "關閉時最小化到托盤",
        "remember_last_selection": "記住上次選擇的版本",
        "settings_group_download": "下載管理",
        "settings_group_path": "路徑管理",
        "theme_mode": "應用主題",
        "theme_light": "淺色",
        "theme_dark": "深色",
        "theme_auto": "跟隨系統",
        "lang": "界面語言",
        "downloader_engine": "下載引擎",
        "fetch_limit": "版本顯示數量",
        "keep_archive": "保留 Eden 壓縮包",
        "disable_ipv6": "禁用 IPv6 (Aria2)",
        "aria2_verbose_log": "詳細日誌 (Aria2)",
        "backup_path": "存檔備份位置",
        "firmware_path": "固件保存位置",
        "keep_firmware_archive": "固件安裝後保留壓縮包",
        "verify_firmware_checksum": "校驗固件完整性 (SHA256)",
        "dl_auto": "自動 (優先 Aria2)",
        "dl_requests": "內部 (Python Requests)",
        "open_user_folder": "打開 Eden 配置資料夾",
        "open_eden_folder": "打開 Eden 模擬器資料夾",
        "user_folder_not_found": "未找到 Eden 配置資料夾",
        "project_desc": "EmuMan 是一個開源的 Eden 模擬器多版本管理工具，支持便捷切換與測試不同版本的性能表現，並簡化安裝、更新及固件管理流程。",
        "view_on_github": "查看源碼",
        "report_issue": "反饋問題",
        "credits": "Credits",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        "firmware_manager": "固件管理",
        "firmware_manager_desc": "管理本地已下載的固件版本，支持手動安裝和更新檢測。",
        "firmware_local_versions": "本地固件: {}",
        "firmware_check_update": "檢查更新",
        "firmware_install_local": "安裝",
        "firmware_no_local": "無本地固件",
        "firmware_select_file": "選擇固件文件",
        "open_firmware_folder": "打開固件資料夾",
        "save_manager": "存檔管理",
        "save_manager_desc": "安全地備份與還原您的遊戲存檔數據。",
        "save_backup": "新建備份",
        "save_restore": "還原存檔",
        "backup_success": "備份創建成功",
        "backup_saved_title": "備份成功",
        "backup_saved_msg": "存檔已備份至：\n{}",
        "restore_confirm": "確定要還原此備份嗎？\n當前存檔將被覆蓋且無法找回！",
        "restore_success": "存檔還原成功",
        "delete_confirm": "確定要刪除此備份文件嗎？",
        "delete_confirm_title": "確認刪除",
        "open_backup_folder": "打開備份資料夾",
        "last_backup": "上次備份：{}",
        "last_backup_none": "上次備份：無",
        "col_date": "日期",
        "col_name": "文件名",
        "col_version": "版本",
        "col_status": "狀態",
        "col_size": "大小",
        "tag_local": "本地",
        "tag_remote": "遠程",
        "tag_installed": "已安裝",
        "no_backups_found": "未找到備份文件",
        "backup_failed": "備份失敗",
        "restore_failed": "還原失敗",
        "mod_installed_count": "已安裝模組: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "已導入 {} 個文件",

        "keys_manager": "密鑰管理",
        "keys_manager_desc": "管理模擬器解密密鑰 (prod.keys/title.keys)",
        "keys_status_found": "已安裝",
        "keys_status_missing": "缺失",
        "import_keys": "導入密鑰",
        "auto_scan_keys": "自動掃描",
        "open_keys_folder": "打開密鑰資料夾",
        "keys_imported": "密鑰導入成功",
        "keys_import_failed": "導入失敗",
        "scan_result": "共找到 {} 個密鑰文件，是否全部導入？",
        "no_keys_found": "未在常見路徑通過掃描找到密鑰",
        "mod_manager": "Mod 管理",
        "mod_manager_desc": "查看與管理已安裝的 Mod (LayeredFS)",
        "open_mod_folder": "打開 Mod 資料夾",
        "no_mods_found": "未檢測到 Mod",
        "mod_enabled": "已啟用",
        "mod_disabled": "已禁用",
        "toggle_mod": "切換開關",
        # Log Manager
        "log_manager": "日誌管理",
        "log_manager_desc": "管理 Eden 模擬器日誌，可導出日誌以便反饋問題。",
        "export_logs": "導出日誌",
        "open_log_dir": "打開日誌目錄",
        "log_export_success": "日誌已成功導出到：\n{}",
        "log_export_fail": "導出日誌失敗：\n{}",
        "on": "開",
        "off": "關",
        "no_build": "未找到構建",
        "log_folder_empty": "日誌目錄為空。",
        "create_folder_fail": "無法創建資料夾: {}",
        "exe_not_found": "找不到可執行文件: {}",
        "create_dir_fail": "創建目錄失敗: {}\n{}",
    },
    "ja": {
        "home": "ホーム",
        "settings": "設定",
        "about": "情報",
        "toolbox": "ツールボックス",
        "open_navigation": "ナビゲーションを開く",
        "cancel": "キャンセル",
        "delete": "削除",
        "confirm_overwrite": "上書き",
        "file_not_found": "ローカルファイルが見つかりません",
        "network_error": "ネットワークエラー",
        "tray_show": "EmuMan を表示",
        "tray_launch_master": "Eden Master を起動",
        "tray_launch_nightly": "Eden Nightly を起動",
        "tray_open_dir": "フォルダを開く",
        "tray_open_eden_dir": "Eden エミュレータフォルダ",
        "tray_open_user_dir": "Eden 設定フォルダ",
        "tray_open_firmware_dir": "ファームウェア保存先",
        "tray_open_backup_dir": "バックアップ保存先",
        "tray_exit": "終了",
        "error": "エラー",
        "warning": "警告",
        "success": "成功",
        "done": "完了",
        "ok": "OK",
        "close": "閉じる",
        "loading": "読み込み中...",
        "online": "オンライン",
        "not_found": "未検出",

        "status_none": "ステータス: 未検出",
        "status_ready": "ステータス: 準備完了",
        "status_prefix": "現在: ",
        "status_unknown": "不明",
        "status_not_installed": "未インストール",
        "eden_path": "Eden パス",
        "browse": "参照",
        "stable_tag": "安定版",
        "dev_tag": "開発版",
        "changelog_placeholder": "バージョンを選択して更新履歴を表示...",
        "master_channel": "Master ブランチ",
        "nightly_channel": "Nightly ブランチ",
        "launch": "起動",
        "download_btn": "ダウンロード",
        "select_download": "複数のビルドが検出されました、ダウンロードを確認してください:",
        "no_platform_build": "このリリースにはお使いのプラットフォーム用のビルドがありません",
        "sync_data": "最新バージョン情報を同期中...",
        "sync_data_success": "同期成功",
        "sync_data_latest": "バージョンリストは最新です",
        "refresh_data": "リストを更新",
        "download_preparing": "ダウンロード準備中",
        "downloading": "ダウンロード中...",
        "download_cancelled": "ダウンロードキャンセル",
        "download_success": "エミュレータ準備完了",
        "download_failed": "ダウンロード失敗",
        "extract_manual": "手動解凍が必要",
        "extract_manual_msg": ".7z ファイルは手動解凍が必要です。保存先:",
        "launch_error": "起動エラー",
        "launch_failed": "起動に失敗しました",
        "config_missing": "設定が見つかりません",
        "config_missing_msg": "Eden エミュレータのパスが設定されていません。\n今すぐ設定しますか？",
        "path_exists": "ファイルが存在します",
        "path_exists_msg": "対象フォルダは既に存在します。上書きしますか？\n\n注意: 旧バージョンは削除されます。",
        "update_app_title": "ソフトウェア更新",
        "update_app_msg": "新しいバージョンが検出されました。今すぐ更新して再起動しますか？",
        "firmware_version": "Eden ファームウェア: {}",
        "firmware_not_detected": "ファームウェア未検出",
        "firmware_update_available": "ファームウェア更新あり: {}",
        "firmware_install_title": "ファームウェアのインストール",
        "firmware_install_confirm": "ファームウェア {} をダウンロードしてインストールしますか？",
        "firmware_update_hint": " (更新: {})",
        "firmware_install_confirm_local": "ファームウェア {} をインストールしますか？",
        "firmware_already_installed": "バージョン {} は既にインストールされています。\n再インストールしますか？",
        "firmware_downloading": "ファームウェアをダウンロード中...",
        "firmware_installing": "ファームウェアをインストール中...",
        "firmware_install_success": "ファームウェアをインストールしました",
        "firmware_install_failed": "インストール失敗",
        "firmware_verifying": "整合性を確認中...",
        "firmware_restart_title": "再起動が必要",
        "firmware_restart_msg": "ファームウェアが正常にインストールされました。\n\n今すぐ Eden を起動してインストールを確認しますか？",
        "start_eden": "Eden を起動",
        "later": "後で",
        "please_launch_eden": "インストールを完了するために Eden を起動してください。",
        "cancelling": "キャンセル中...",
        "firmware_install_please_wait": "お待ちください...",
        "settings_group_app": "アプリ設定",
        "check_update_start": "起動時に更新を確認",
        "minimize_to_tray": "トレイに最小化",
        "remember_last_selection": "前回のバージョン選択を記憶",
        "settings_group_download": "ダウンロード管理",
        "settings_group_path": "パス管理",
        "theme_mode": "テーマ",
        "theme_light": "ライト",
        "theme_dark": "ダーク",
        "theme_auto": "システム",
        "lang": "言語",
        "downloader_engine": "ダウンロードエンジン",
        "fetch_limit": "表示件数",
        "keep_archive": "Eden アーカイブを保持",
        "disable_ipv6": "IPv6 を無効化 (Aria2)",
        "aria2_verbose_log": "詳細ログ (Aria2)",
        "backup_path": "バックアップ保存先",
        "firmware_path": "ファームウェア保存先",
        "keep_firmware_archive": "ファームウェアアーカイブを保持",
        "verify_firmware_checksum": "ファームウェア整合性確認 (SHA256)",
        "dl_auto": "自動 (Aria2 推奨)",
        "dl_requests": "内部 (Python Requests)",
        "open_user_folder": "ユーザーフォルダを開く",
        "open_eden_folder": "エミュレータフォルダを開く",
        "user_folder_not_found": "ユーザーフォルダが見つかりません",
        "project_desc": "EmuMan は Eden エミュレータ用のオープンソースバージョン管理ツールです。",
        "view_on_github": "ソースコード",
        "report_issue": "問題を報告",
        "credits": "クレジット",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        "firmware_manager": "ファームウェア管理",
        "firmware_manager_desc": "ファームウェアの管理・インストール・更新確認。",
        "firmware_local_versions": "ローカル: {}",
        "firmware_check_update": "更新確認",
        "firmware_install_local": "インストール",
        "firmware_no_local": "ローカルなし",
        "firmware_select_file": "ファイルを選択",
        "open_firmware_folder": "フォルダを開く",
        "save_manager": "セーブデータ管理",
        "save_manager_desc": "セーブデータのバックアップと復元。",
        "save_backup": "新規バックアップ",
        "save_restore": "復元",
        "backup_success": "バックアップ成功",
        "backup_saved_title": "バックアップ完了",
        "backup_saved_msg": "保存先:\n{}",
        "restore_confirm": "このバックアップを復元しますか？\n現在のデータは上書きされます！",
        "restore_success": "復元成功",
        "delete_confirm": "このバックアップを削除しますか？",
        "delete_confirm_title": "削除の確認",
        "open_backup_folder": "フォルダを開く",
        "last_backup": "最終: {}",
        "last_backup_none": "なし",
        "col_date": "日付",
        "col_name": "名前",
        "col_version": "バージョン",
        "col_status": "状態",
        "col_size": "サイズ",
        "tag_local": "ローカル",
        "tag_remote": "リモート",
        "tag_installed": "導入済",
        "no_backups_found": "バックアップなし",
        "backup_failed": "バックアップ失敗",
        "restore_failed": "復元失敗",
        "mod_installed_count": "インストール済みMOD: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "{} 個のファイルをインポートしました",

        "keys_manager": "キー管理",
        "keys_manager_desc": "エミュレータキー (prod.keys/title.keys) の管理",
        "keys_status_found": "導入済",
        "keys_status_missing": "未導入",
        "import_keys": "キーをインポート",
        "auto_scan_keys": "自動スキャン",
        "open_keys_folder": "フォルダを開く",
        "keys_imported": "インポート成功",
        "keys_import_failed": "インポート失敗",
        "scan_result": "{} 個のキーが見つかりました、インポートしますか？",
        "no_keys_found": "キーが見つかりませんでした",
        "mod_manager": "Mod 管理",
        "mod_manager_desc": "Mod の管理 (LayeredFS)",
        "open_mod_folder": "フォルダを開く",
        "no_mods_found": "Mod なし",
        "mod_enabled": "有効",
        "mod_disabled": "無効",
        # Log Manager
        "log_manager": "ログ管理",
        "log_manager_desc": "Eden エミュレータログを管理し、問題報告のためにエクスポートします。",
        "export_logs": "ログのエクスポート",
        "open_log_dir": "ログフォルダを開く",
        "log_export_success": "ログが正常にエクスポートされました：\n{}",
        "log_export_fail": "ログのエクスポートに失敗しました：\n{}",
        "toggle_mod": "切り替え",
        "on": "オン",
        "off": "オフ",
        "no_build": "ビルドなし",
        "log_folder_empty": "ログフォルダが空です。",
        "create_folder_fail": "フォルダを作成できませんでした: {}",
        "exe_not_found": "実行ファイルが見つかりません: {}",
        "create_dir_fail": "ディレクトリの作成に失敗しました: {}\n{}",
    },
    "ko": {
        "home": "홈",
        "settings": "설정",
        "about": "정보",
        "toolbox": "도구 상자",
        "open_navigation": "네비게이션 열기",
        "cancel": "취소",
        "delete": "삭제",
        "confirm_overwrite": "덮어쓰기",
        "file_not_found": "로컬 파일을 찾을 수 없습니다",
        "network_error": "네트워크 오류",
        "tray_show": "EmuMan 표시",
        "tray_launch_master": "Eden Master 실행",
        "tray_launch_nightly": "Eden Nightly 실행",
        "tray_open_dir": "폴더 열기",
        "tray_open_eden_dir": "Eden 에뮬레이터 폴더",
        "tray_open_user_dir": "Eden 설정 폴더",
        "tray_open_firmware_dir": "펌웨어 저장소",
        "tray_open_backup_dir": "백업 저장소",
        "tray_exit": "종료",
        "error": "오류",
        "warning": "경고",
        "success": "성공",
        "done": "완료",
        "ok": "확인",
        "close": "닫기",
        "loading": "불러오는 중...",
        "online": "온라인",
        "not_found": "찾을 수 없음",

        "status_none": "상태: 에뮬레이터 없음",
        "status_ready": "상태: Eden 준비됨",
        "status_prefix": "현재: ",
        "status_unknown": "알 수 없음",
        "status_not_installed": "설치되지 않음",
        "eden_path": "Eden 경로",
        "browse": "찾아보기",
        "stable_tag": "안정판",
        "dev_tag": "개발판",
        "changelog_placeholder": "버전을 선택하여 변경 로그 보기...",
        "master_channel": "Master 채널",
        "nightly_channel": "Nightly 채널",
        "launch": "실행",
        "download_btn": "다운로드",
        "select_download": "여러 빌드가 감지되었습니다. 다운로드를 확인하세요:",
        "no_platform_build": "이 플랫폼에 사용할 수 있는 빌드가 없습니다",
        "sync_data": "최신 버전 정보 동기화 중...",
        "sync_data_success": "동기화 성공",
        "sync_data_latest": "최신 상태입니다",
        "refresh_data": "새로고침",
        "download_preparing": "다운로드 준비 중",
        "downloading": "다운로드 중...",
        "download_cancelled": "다운로드 취소됨",
        "download_success": "준비 완료",
        "download_failed": "다운로드 실패",
        "extract_manual": "수동 압축 해제 필요",
        "extract_manual_msg": ".7z 파일은 수동으로 압축을 풀어야 합니다. 저장 위치:",
        "launch_error": "실행 오류",
        "launch_failed": "실행 실패",
        "config_missing": "설정 없음",
        "config_missing_msg": "Eden 경로가 설정되지 않았습니다.\n지금 설정하시겠습니까?",
        "path_exists": "파일 존재함",
        "path_exists_msg": "대상 폴더가 이미 존재합니다. 덮어쓰시겠습니까?\n\n구버전은 삭제됩니다.",
        "update_app_title": "소프트웨어 업데이트",
        "update_app_msg": "새 버전이 감지되었습니다. 업데이트하고 재시작하시겠습니까?",
        "firmware_version": "Eden 펌웨어: {}",
        "firmware_not_detected": "펌웨어 없음",
        "firmware_update_available": "펌웨어 업데이트 가능: {}",
        "firmware_install_title": "펌웨어 설치",
        "firmware_install_confirm": "펌웨어 {}를 다운로드하고 설치하시겠습니까?",
        "firmware_update_hint": " (업데이트: {})",
        "firmware_install_confirm_local": "펌웨어 {}를 설치하시겠습니까?",
        "firmware_already_installed": "버전 {}가 이미 설치되어 있습니다.\n재설치하시겠습니까?",
        "firmware_downloading": "펌웨어 다운로드 중...",
        "firmware_installing": "펌웨어 설치 중...",
        "firmware_install_success": "설치 성공",
        "firmware_install_failed": "설치 실패",
        "firmware_verifying": "무결성 확인 중...",
        "firmware_restart_title": "재시작 필요",
        "firmware_restart_msg": "펌웨어가 성공적으로 설치되었습니다.\n\n지금 Eden을 실행하여 설치를 확인하시겠습니까?",
        "start_eden": "Eden 실행",
        "later": "나중에",
        "please_launch_eden": "설치를 완료하려면 Eden을 실행하세요.",
        "cancelling": "취소 중...",
        "firmware_install_please_wait": "잠시만 기다려주세요...",
        "settings_group_app": "애플리케이션 설정",
        "check_update_start": "시작 시 업데이트 확인",
        "minimize_to_tray": "트레이로 최소화",
        "remember_last_selection": "마지막 선택 버전 기억",
        "settings_group_download": "다운로드 관리",
        "settings_group_path": "경로 관리",
        "theme_mode": "테마",
        "theme_light": "라이트",
        "theme_dark": "다크",
        "theme_auto": "시스템",
        "lang": "언어",
        "downloader_engine": "다운로드 엔진",
        "fetch_limit": "표시 개수",
        "keep_archive": "Eden 아카이브 유지",
        "disable_ipv6": "IPv6 비활성화 (Aria2)",
        "aria2_verbose_log": "상세 로그 (Aria2)",
        "backup_path": "백업 경로",
        "firmware_path": "펌웨어 경로",
        "keep_firmware_archive": "펌웨어 아카이브 유지",
        "verify_firmware_checksum": "펌웨어 무결성 검사 (SHA256)",
        "dl_auto": "자동 (Aria2 권장)",
        "dl_requests": "내부 (Python Requests)",
        "open_user_folder": "사용자 폴더 열기",
        "open_eden_folder": "에뮬레이터 폴더 열기",
        "user_folder_not_found": "사용자 폴더를 찾을 수 없습니다",
        "project_desc": "EmuMan은 Eden 에뮬레이터를 위한 오픈 소스 버전 관리 도구입니다.",
        "view_on_github": "소스 코드",
        "report_issue": "문제 신고",
        "credits": "크레딧",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        "firmware_manager": "펌웨어 관리자",
        "firmware_manager_desc": "로컬 펌웨어 관리 및 설치.",
        "firmware_local_versions": "로컬: {}",
        "firmware_check_update": "업데이트 확인",
        "firmware_install_local": "설치",
        "firmware_no_local": "로컬 펌웨어 없음",
        "firmware_select_file": "파일 선택",
        "open_firmware_folder": "폴더 열기",
        "save_manager": "세이브 관리자",
        "save_manager_desc": "세이브 데이터 백업 및 복원.",
        "save_backup": "새 백업",
        "save_restore": "복원",
        "backup_success": "백업 성공",
        "backup_saved_title": "백업 완료",
        "backup_saved_msg": "저장됨:\n{}",
        "restore_confirm": "이 백업을 복원하시겠습니까?\n현재 데이터는 덮어씌워집니다!",
        "restore_success": "복원 성공",
        "delete_confirm": "이 백업을 삭제하시겠습니까?",
        "delete_confirm_title": "삭제 확인",
        "open_backup_folder": "폴더 열기",
        "last_backup": "최근: {}",
        "last_backup_none": "없음",
        "col_date": "날짜",
        "col_name": "이름",
        "col_version": "버전",
        "col_status": "상태",
        "col_size": "크기",
        "tag_local": "로컬",
        "tag_remote": "원격",
        "tag_installed": "설치됨",
        "no_backups_found": "백업 없음",
        "backup_failed": "백업 실패",
        "restore_failed": "복원 실패",
        "mod_installed_count": "설치된 모드: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "{}개 파일을 가져왔습니다",

        "keys_manager": "키 관리자",
        "keys_manager_desc": "에뮬레이터 키 (prod.keys/title.keys) 관리",
        "keys_status_found": "설치됨",
        "keys_status_missing": "없음",
        "import_keys": "키 가져오기",
        "auto_scan_keys": "자동 스캔",
        "open_keys_folder": "폴더 열기",
        "keys_imported": "가져오기 성공",
        "keys_import_failed": "가져오기 실패",
        "scan_result": "{}개의 키 파일을 찾았습니다. 가져오시겠습니까?",
        "no_keys_found": "키를 찾을 수 없습니다",
        "mod_manager": "모드 관리자",
        "mod_manager_desc": "모드 관리 (LayeredFS)",
        "open_mod_folder": "폴더 열기",
        "no_mods_found": "모드 없음",
        "mod_enabled": "사용",
        "mod_disabled": "사용 안 함",
        "toggle_mod": "토글",
        # Log Manager
        "log_manager": "로그 관리",
        "log_manager_desc": "Eden 에뮬레이터 로그를 관리하고 문제 보고를 위해 내보냅니다.",
        "export_logs": "로그 내보내기",
        "open_log_dir": "로그 폴더 열기",
        "log_export_success": "로그를 성공적으로 내보냈습니다:\n{}",
        "log_export_fail": "로그 내보내기 실패:\n{}",
        "on": "켜기",
        "off": "끄기",
        "log_folder_empty": "로그 폴더가 비어 있습니다.",
        "create_folder_fail": "폴더를 생성할 수 없습니다: {}",
        "exe_not_found": "실행 파일을 찾을 수 없습니다: {}",
        "create_dir_fail": "디렉토리를 생성하지 못했습니다: {}\n{}",
    },
    "ru": {
        "home": "Главная",
        "settings": "Настройки",
        "about": "О программе",
        "toolbox": "Инструменты",
        "open_navigation": "Открыть навигацию",
        "cancel": "Отмена",
        "delete": "Удалить",
        "confirm_overwrite": "Перезаписать",
        "file_not_found": "Файл не найден",
        "network_error": "Ошибка сети",
        "tray_show": "Показать EmuMan",
        "tray_launch_master": "Запуск Eden Master",
        "tray_launch_nightly": "Запуск Eden Nightly",
        "tray_open_dir": "Открыть папку",
        "tray_open_eden_dir": "Папка эмулятора",
        "tray_open_user_dir": "Папка настроек",
        "tray_open_firmware_dir": "Папка прошивок",
        "tray_open_backup_dir": "Папка бэкапов",
        "tray_exit": "Выход",
        "error": "Ошибка",
        "warning": "Предупреждение",
        "success": "Успешно",
        "done": "Готово",
        "ok": "ОК",
        "close": "Закрыть",
        "loading": "Загрузка...",
        "online": "Онлайн",
        "not_found": "Не найдено",

        "status_none": "Статус: Не найдено",
        "status_ready": "Статус: Готов",
        "status_prefix": "Текущая: ",
        "status_not_installed": "Не установлено",
        "eden_path": "Путь к Eden",
        "browse": "Обзор",
        "stable_tag": "Стабильная",
        "dev_tag": "Dev",
        "changelog_placeholder": "Выберите версию для просмотра изменений...",
        "master_channel": "Канал Master",
        "nightly_channel": "Канал Nightly",
        "launch": "Запуск",
        "download_btn": "Скачать",
        "select_download": "Найдено несколько сборок, выберите:",
        "no_platform_build": "Нет сборок для вашей платформы",
        "sync_data": "Синхронизация...",
        "sync_data_success": "Успешно",
        "sync_data_latest": "Список версий обновлен",
        "refresh_data": "Обновить список",
        "download_preparing": "Подготовка",
        "downloading": "Скачивание...",
        "download_cancelled": "Отменено",
        "download_success": "Готово",
        "download_failed": "Ошибка скачивания",
        "extract_manual": "Требуется ручная распаковка",
        "extract_manual_msg": "Файл .7z требует ручной распаковки. Сохранен как",
        "launch_error": "Ошибка запуска",
        "launch_failed": "Сбой запуска",
        "config_missing": "Нет конфигурации",
        "config_missing_msg": "Путь к Eden не настроен. Настроить сейчас?",
        "path_exists": "Файл существует",
        "path_exists_msg": "Папка существует. Перезаписать?\n\nСтарая версия будет удалена.",
        "update_app_title": "Обновление",
        "update_app_msg": "Найдена новая версия. Обновить и перезапустить?",
        "firmware_version": "Прошивка Eden: {}",
        "firmware_not_detected": "Прошивка не найдена",
        "firmware_update_available": "Доступно обновление ПО: {}",
        "firmware_install_title": "Установка ПО",
        "firmware_install_confirm": "Скачать и установить ПО {}?",
        "firmware_update_hint": " (Обновление: {})",
        "firmware_install_confirm_local": "Установить ПО {}?",
        "firmware_already_installed": "Версия {} уже установлена. Переустановить?",
        "firmware_downloading": "Скачивание прошивки...",
        "firmware_installing": "Установка...",
        "firmware_install_success": "Успешно",
        "firmware_install_failed": "Ошибка",
        "firmware_verifying": "Проверка целостности...",
        "firmware_restart_title": "Требуется перезапуск",
        "firmware_restart_msg": "Прошивка успешно установлена.\n\nЗапустить Eden сейчас для проверки?",
        "start_eden": "Запустить Eden",
        "later": "Позже",
        "please_launch_eden": "Пожалуйста, запустите Eden для завершения проверки.",
        "cancelling": "Отмена...",
        "firmware_install_please_wait": "Подождите...",
        "settings_group_app": "Настройки приложения",
        "check_update_start": "Проверять обновления при запуске",
        "minimize_to_tray": "Сворачивать в трей",
        "remember_last_selection": "Запоминать выбор версии",
        "settings_group_download": "Загрузки",
        "settings_group_path": "Пути",
        "theme_mode": "Тема",
        "theme_light": "Светлая",
        "theme_dark": "Тёмная",
        "theme_auto": "Системная",
        "lang": "Язык",
        "downloader_engine": "Движок загрузки",
        "fetch_limit": "Лимит версий",
        "keep_archive": "Сохранять архивы Eden",
        "disable_ipv6": "Отключить IPv6 (Aria2)",
        "aria2_verbose_log": "Подробный лог (Aria2)",
        "backup_path": "Путь к бэкапам",
        "firmware_path": "Путь к прошивкам",
        "keep_firmware_archive": "Сохранять архивы ПО",
        "verify_firmware_checksum": "Проверка SHA256",
        "dl_auto": "Авто (Aria2)",
        "dl_requests": "Встроенный (Requests)",
        "open_user_folder": "Открыть папку данных",
        "open_eden_folder": "Открыть папку эмулятора",
        "user_folder_not_found": "Папка не найдена",
        "project_desc": "EmuMan - менеджер версий для эмулятора Eden.",
        "view_on_github": "Исходный код",
        "report_issue": "Сообщить о проблеме",
        "credits": "Авторы",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        "firmware_manager": "Менеджер прошивок",
        "firmware_manager_desc": "Управление прошивками.",
        "firmware_local_versions": "Локально: {}",
        "firmware_check_update": "Проверить",
        "firmware_install_local": "Установить",
        "firmware_no_local": "Нет файлов",
        "firmware_select_file": "Выбрать файл",
        "open_firmware_folder": "Открыть папку",
        "save_manager": "Менеджер сохранений",
        "save_manager_desc": "Резервное копирование сохранений.",
        "save_backup": "Создать бэкап",
        "save_restore": "Восстановить",
        "backup_success": "Успешно",
        "backup_saved_title": "Успешно",
        "backup_saved_msg": "Сохранено в:\n{}",
        "restore_confirm": "Восстановить этот бэкап?\nТекущие данные будут удалены!",
        "restore_success": "Восстановлено",
        "delete_confirm": "Удалить этот бэкап?",
        "delete_confirm_title": "Подтверждение удаления",
        "open_backup_folder": "Открыть папку",
        "last_backup": "Последний: {}",
        "last_backup_none": "Нет",
        "col_date": "Дата",
        "col_name": "Имя",
        "col_version": "Версия",
        "col_status": "Статус",
        "col_size": "Размер",
        "tag_local": "Локально",
        "tag_remote": "Удаленно",
        "tag_installed": "Установлено",
        "no_backups_found": "Нет бэкапов",
        "backup_failed": "Ошибка бэкапа",
        "restore_failed": "Ошибка восстановления",
        "mod_installed_count": "Установлено модов: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "Импортировано файлов: {}",

        "keys_manager": "Ключи",
        "keys_manager_desc": "Управление ключами (prod.keys)",
        "keys_status_found": "Установлено",
        "keys_status_missing": "Отсутствует",
        "import_keys": "Импорт",
        "auto_scan_keys": "Автоскан",
        "open_keys_folder": "Открыть папку",
        "keys_imported": "Успешно",
        "keys_import_failed": "Ошибка",
        "scan_result": "Найдено ключей: {}. Импортировать?",
        "no_keys_found": "Не найдено",
        "mod_manager": "Моды",
        "mod_manager_desc": "Упвравление модами (LayeredFS)",
        "open_mod_folder": "Открыть папку",
        "no_mods_found": "Нет модов",
        "mod_enabled": "Вкл",
        "mod_disabled": "Выкл",
        "toggle_mod": "Переключить",
        # Log Manager
        "log_manager": "Управление журналами",
        "log_manager_desc": "Управление журналами приложения, экспорт для отчетов об ошибках.",
        "export_logs": "Экспорт журналов",
        "open_log_dir": "Открыть папку журналов",
        "log_export_success": "Журналы успешно экспортированы в:\n{}",
        "log_export_fail": "Ошибка экспорта журналов:\n{}",
        "on": "Вкл",
        "off": "Выкл",
        "no_build": "Сборка не найдена",
        "log_folder_empty": "Папка с логами пуста.",
        "create_folder_fail": "Не удалось создать папку: {}",
        "exe_not_found": "Исполняемый файл не найден: {}",
        "create_dir_fail": "Не удалось создать директорию: {}\n{}",
    },
    "pt": {
        "home": "Início",
        "settings": "Configurações",
        "about": "Sobre",
        "toolbox": "Ferramentas",
        "open_navigation": "Abrir Navegação",
        "cancel": "Cancelar",
        "delete": "Apagar",
        "confirm_overwrite": "Sobrescrever",
        "file_not_found": "Arquivo não encontrado",
        "network_error": "Erro de rede",
        "tray_show": "Mostrar EmuMan",
        "tray_launch_master": "Iniciar Master",
        "tray_launch_nightly": "Iniciar Nightly",
        "tray_open_dir": "Abrir pasta",
        "tray_open_eden_dir": "Pasta do Emulador",
        "tray_open_user_dir": "Pasta de Configuração",
        "tray_open_firmware_dir": "Pasta de Firmware",
        "tray_open_backup_dir": "Pasta de Backup",
        "tray_exit": "Sair",
        "error": "Erro",
        "warning": "Aviso",
        "success": "Sucesso",
        "done": "Concluído",
        "ok": "OK",
        "close": "Fechar",
        "loading": "Carregando...",
        "online": "Online",
        "not_found": "Não encontrado",

        "status_none": "Status: Não encontrado",
        "status_ready": "Status: Pronto",
        "status_prefix": "Atual: ",
        "status_not_installed": "Não instalado",
        "eden_path": "Caminho do Eden",
        "browse": "Procurar",
        "stable_tag": "Estável",
        "dev_tag": "Dev",
        "changelog_placeholder": "Selecione uma versão...",
        "master_channel": "Canal Master",
        "nightly_channel": "Canal Nightly",
        "launch": "Iniciar",
        "download_btn": "Baixar",
        "select_download": "Múltiplas versões detectadas:",
        "no_platform_build": "Sem versão para sua plataforma",
        "sync_data": "Sincronizando...",
        "sync_data_success": "Sucesso",
        "sync_data_latest": "Lista atualizada",
        "refresh_data": "Atualizar lista",
        "download_preparing": "Preparando",
        "downloading": "Baixando...",
        "download_cancelled": "Cancelado",
        "download_success": "Pronto",
        "download_failed": "Falha",
        "extract_manual": "Extração manual necessária",
        "extract_manual_msg": "Arquivo .7z requer extração manual. Salvo como",
        "launch_error": "Erro ao iniciar",
        "launch_failed": "Falha ao iniciar",
        "config_missing": "Configuração ausente",
        "config_missing_msg": "Caminho não configurado. Configurar agora?",
        "path_exists": "Arquivo existe",
        "path_exists_msg": "Diretório existe. Sobrescrever?\n\nVersão antiga será apagada.",
        "update_app_title": "Atualização",
        "update_app_msg": "Nova versão detectada. Atualizar e reiniciar?",
        "firmware_version": "Firmware Eden: {}",
        "firmware_not_detected": "Firmware não detectado",
        "firmware_update_available": "Atualização disponível: {}",
        "firmware_install_title": "Instalar Firmware",
        "firmware_install_confirm": "Baixar e instalar firmware {}?",
        "firmware_update_hint": " (Atualização: {})",
        "firmware_install_confirm_local": "Instalar firmware {}?",
        "firmware_already_installed": "Versão {} já instalada. Reinstalar?",
        "firmware_downloading": "Baixando firmware...",
        "firmware_installing": "Instalando...",
        "firmware_install_success": "Instalado com sucesso",
        "firmware_install_failed": "Falha na instalação",
        "firmware_verifying": "Verificando integridade...",
        "firmware_restart_title": "Reinício necessário",
        "firmware_restart_msg": "Firmware instalado com sucesso.\n\nIniciar Eden agora para verificar?",
        "start_eden": "Iniciar Eden",
        "later": "Depois",
        "please_launch_eden": "Por favor, inicie o Eden para concluir a verificação.",
        "cancelling": "Cancelando...",
        "firmware_install_please_wait": "Aguarde...",
        "settings_group_app": "Aplicativo",
        "check_update_start": "Verificar atualizações ao iniciar",
        "minimize_to_tray": "Minimizar para bandeja",
        "remember_last_selection": "Lembrar última seleção",
        "settings_group_download": "Downloads",
        "settings_group_path": "Caminhos",
        "theme_mode": "Tema",
        "theme_light": "Claro",
        "theme_dark": "Escuro",
        "theme_auto": "Sistema",
        "lang": "Idioma",
        "downloader_engine": "Motor de Download",
        "fetch_limit": "Limite de versões",
        "keep_archive": "Manter arquivos Eden",
        "disable_ipv6": "Desativar IPv6",
        "aria2_verbose_log": "Log detalhado (Aria2)",
        "backup_path": "Caminho de Backup",
        "firmware_path": "Caminho de Firmware",
        "keep_firmware_archive": "Manter arquivo de firmware",
        "verify_firmware_checksum": "Verificar integridade (SHA256)",
        "dl_auto": "Auto (Aria2)",
        "dl_requests": "Interno (Requests)",
        "open_user_folder": "Abrir pasta de dados",
        "open_eden_folder": "Abrir pasta do emulador",
        "user_folder_not_found": "Pasta não encontrada",
        "project_desc": "Gerenciador de versões código aberto para Eden.",
        "view_on_github": "Código Fonte",
        "report_issue": "Relatar problema",
        "credits": "Créditos",
        "copyright": "Copyright © 2024 EmuMan Team. MIT License.",
        "firmware_manager": "Gerenciador de Firmware",
        "firmware_manager_desc": "Gerenciar firmwares.",
        "firmware_local_versions": "Local: {}",
        "firmware_check_update": "Verificar",
        "firmware_install_local": "Instalar",
        "firmware_no_local": "Sem firmware local",
        "firmware_select_file": "Selecionar arquivo",
        "open_firmware_folder": "Abrir pasta",
        "save_manager": "Gerenciador de Saves",
        "save_manager_desc": "Backup e restauração de saves.",
        "save_backup": "Novo Backup",
        "save_restore": "Restaurar",
        "backup_success": "Sucesso",
        "backup_saved_title": "Sucesso",
        "backup_saved_msg": "Salvo em:\n{}",
        "restore_confirm": "Restaurar este backup?\nDados atuais serão perdidos!",
        "restore_success": "Restaurado com sucesso",
        "delete_confirm": "Apagar este backup?",
        "delete_confirm_title": "Confirmar exclusão",
        "open_backup_folder": "Abrir pasta",
        "last_backup": "Último: {}",
        "last_backup_none": "Nenhum",
        "col_date": "Data",
        "col_name": "Nome",
        "col_version": "Versão",
        "col_status": "Status",
        "col_size": "Tamanho",
        "tag_local": "Local",
        "tag_remote": "Remoto",
        "tag_installed": "Instalado",
        "no_backups_found": "Nenhum backup",
        "backup_failed": "Falha no backup",
        "restore_failed": "Falha na restauração",
        "mod_installed_count": "Mods instalados: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "Importados {} arquivos",

        "keys_manager": "Chaves",
        "keys_manager_desc": "Gerenciar chaves (prod.keys)",
        "keys_status_found": "Instalado",
        "keys_status_missing": "Ausente",
        "import_keys": "Importar",
        "auto_scan_keys": "Auto Escanear",
        "open_keys_folder": "Abrir pasta",
        "keys_imported": "Sucesso",
        "keys_import_failed": "Falha",
        "scan_result": "Encontradas {} chaves. Importar?",
        "no_keys_found": "Nenhuma chave encontrada",
        "mod_manager": "Mods",
        "mod_manager_desc": "Gerenciar Mods (LayeredFS)",
        "open_mod_folder": "Abrir pasta",
        "no_mods_found": "Sem mods",
        "mod_enabled": "Ativado",
        "mod_disabled": "Desativado",
        # Log Manager
        "log_manager": "Gerenciador de Logs",
        "log_manager_desc": "Gerencie logs do aplicativo, exporte para relatar problemas.",
        "export_logs": "Exportar Logs",
        "open_log_dir": "Abrir Pasta de Logs",
        "log_export_success": "Logs exportados com sucesso para:\n{}",
        "log_export_fail": "Falha ao exportar logs:\n{}",
        "toggle_mod": "Alternar",
        "on": "Ligado",
        "off": "Desligado",
        "no_build": "Sem versão",
        "log_folder_empty": "A pasta de logs está vazia.",
        "create_folder_fail": "Não foi possível criar a pasta: {}",
        "exe_not_found": "Executável não encontrado: {}",
        "create_dir_fail": "Falha ao criar diretório: {}\n{}",
    },
    "fr": {
        "home": "Accueil",
        "settings": "Paramètres",
        "about": "À propos",
        "toolbox": "Boîte à outils",
        "open_navigation": "Ouvrir la navigation",
        "cancel": "Annuler",
        "delete": "Supprimer",
        "confirm_overwrite": "Écraser",
        "file_not_found": "Fichier local introuvable",
        "network_error": "Erreur réseau",
        "tray_show": "Afficher EmuMan",
        "tray_launch_master": "Lancer Master",
        "tray_launch_nightly": "Lancer Nightly",
        "tray_open_dir": "Ouvrir le dossier",
        "tray_open_eden_dir": "Dossier Émulateur Eden",
        "tray_open_user_dir": "Dossier Paramètres Eden",
        "tray_open_firmware_dir": "Dossier Firmware",
        "tray_open_backup_dir": "Dossier Sauvegardes",
        "tray_exit": "Quitter",
        "error": "Erreur",
        "warning": "Avertissement",
        "success": "Succès",
        "done": "Terminé",
        "ok": "OK",
        "close": "Fermer",
        "loading": "Chargement...",
        "online": "En ligne",
        "not_found": "Introuvable",

        "status_none": "Statut: Non trouvé",
        "status_ready": "Statut: Eden Prêt",
        "status_prefix": "Actuel: ",
        "status_not_installed": "Non installé",
        "eden_path": "Chemin Eden",
        "browse": "Parcourir",
        "stable_tag": "Stable",
        "dev_tag": "Dev",
        "changelog_placeholder": "Sélectionnez une version...",
        "master_channel": "Canal Principal",
        "nightly_channel": "Canal Nightly",
        "launch": "Lancer",
        "download_btn": "Télécharger",
        "select_download": "Plusieurs builds détectés:",
        "no_platform_build": "Aucun build pour votre plateforme",
        "sync_data": "Synchronisation...",
        "sync_data_success": "Succès",
        "sync_data_latest": "Liste à jour",
        "refresh_data": "Actualiser",
        "download_preparing": "Préparation",
        "downloading": "Téléchargement...",
        "download_cancelled": "Annulé",
        "download_success": "Prêt",
        "download_failed": "Échec",
        "extract_manual": "Extraction manuelle requise",
        "extract_manual_msg": "Le fichier .7z nécessite une extraction manuelle. Enregistré sous",
        "launch_error": "Erreur de lancement",
        "launch_failed": "Le lancement a échoué",
        "config_missing": "Configuration manquante",
        "config_missing_msg": "Chemin Eden non configuré. Le configurer maintenant ?",
        "path_exists": "Fichier existant",
        "path_exists_msg": "Le dossier existe. Écraser ?\n\nL'ancienne version sera supprimée.",
        "update_app_title": "Mise à jour logicielle",
        "update_app_msg": "Nouvelle version détectée. Mettre à jour et redémarrer ?",
        "firmware_version": "Firmware Eden: {}",
        "firmware_not_detected": "Firmware non détecté",
        "firmware_update_available": "Mise à jour Firmware: {}",
        "firmware_install_title": "Installer Firmware",
        "firmware_install_confirm": "Télécharger et installer le firmware {} ?",
        "firmware_update_hint": " (Mise à jour: {})",
        "firmware_install_confirm_local": "Installer le firmware {} ?",
        "firmware_already_installed": "Version {} déjà installée. Réinstaller ?",
        "firmware_downloading": "Téléchargement du firmware...",
        "firmware_installing": "Installation du firmware...",
        "firmware_install_success": "Succès",
        "firmware_install_failed": "Échec",
        "firmware_verifying": "Vérification de l'intégrité...",
        "firmware_restart_title": "Redémarrage requis",
        "firmware_restart_msg": "Firmware installé avec succès.\n\nLancer Eden maintenant pour vérifier ?",
        "start_eden": "Lancer Eden",
        "later": "Plus tard",
        "please_launch_eden": "Veuillez lancer Eden pour terminer la vérification.",
        "cancelling": "Annulation...",
        "firmware_install_please_wait": "Veuillez patienter...",
        "settings_group_app": "Paramètres de l'application",
        "check_update_start": "Vérifier les mises à jour au démarrage",
        "minimize_to_tray": "Réduire dans la barre d'état système",
        "remember_last_selection": "Mémoriser la dernière version",
        "settings_group_download": "Gestion des téléchargements",
        "settings_group_path": "Gestion des chemins",
        "theme_mode": "Thème",
        "theme_light": "Clair",
        "theme_dark": "Sombre",
        "theme_auto": "Système",
        "lang": "Langue",
        "downloader_engine": "Moteur de téléchargement",
        "fetch_limit": "Limite de récupération",
        "keep_archive": "Conserver les archives Eden",
        "disable_ipv6": "Désactiver IPv6 (Aria2)",
        "aria2_verbose_log": "Journal détaillé (Aria2)",
        "backup_path": "Chemin de sauvegarde",
        "firmware_path": "Chemin du firmware",
        "keep_firmware_archive": "Conserver l'archive du firmware",
        "verify_firmware_checksum": "Vérifier Firmware (SHA256)",
        "dl_auto": "Auto (Aria2)",
        "dl_requests": "Interne (Requests)",
        "open_user_folder": "Ouvrir dossier données",
        "open_eden_folder": "Ouvrir dossier émulateur",
        "user_folder_not_found": "Dossier non trouvé",
        "project_desc": "EmuMan est un gestionnaire de versions open-source pour l'émulateur Eden.",
        "view_on_github": "Code Source",
        "report_issue": "Signaler un problème",
        "credits": "Crédits",
        "copyright": "Copyright © 2024 Équipe EmuMan. Licence MIT.",
        "firmware_manager": "Gestionnaire de Firmware",
        "firmware_manager_desc": "Gérer les firmwares locaux.",
        "firmware_local_versions": "Local: {}",
        "firmware_check_update": "Vérifier",
        "firmware_install_local": "Installer",
        "firmware_no_local": "Aucun firmware local",
        "firmware_select_file": "Sélectionner un fichier",
        "open_firmware_folder": "Ouvrir le dossier",
        "save_manager": "Gestionnaire de Sauvegardes",
        "save_manager_desc": "Sauvegarder et restaurer vos données.",
        "save_backup": "Nouvelle Sauvegarde",
        "save_restore": "Restaurer",
        "backup_success": "Succès",
        "backup_saved_title": "Sauvegarde réussie",
        "backup_saved_msg": "Enregistré dans:\n{}",
        "restore_confirm": "Restaurer cette sauvegarde ?\nLes données actuelles seront écrasées !",
        "restore_success": "Restauration réussie",
        "delete_confirm": "Supprimer cette sauvegarde ?",
        "delete_confirm_title": "Confirmer la suppression",
        "open_backup_folder": "Ouvrir le dossier",
        "last_backup": "Dernière: {}",
        "last_backup_none": "Jamais",
        "col_date": "Date",
        "col_name": "Nom",
        "col_version": "Version",
        "col_status": "Statut",
        "col_size": "Taille",
        "tag_local": "Local",
        "tag_remote": "Distant",
        "tag_installed": "Installé",
        "no_backups_found": "Aucune sauvegarde",
        "backup_failed": "Échec de sauvegarde",
        "restore_failed": "Échec de restauration",
        "mod_installed_count": "Mods installés: {}",
        "keys_status_template": "prod.keys: {} | title.keys: {}",
        "keys_imported_count": "{} fichiers importés",

        "keys_manager": "Gestionnaire de Clés",
        "keys_manager_desc": "Gérer les clés de déchiffrement (prod.keys)",
        "keys_status_found": "Installé",
        "keys_status_missing": "Manquant",
        "import_keys": "Importer",
        "auto_scan_keys": "Scan Auto",
        "open_keys_folder": "Ouvrir le dossier",
        "keys_imported": "Importation réussie",
        "keys_import_failed": "Échec",
        "scan_result": "{} clés trouvées. Importer ?",
        "no_keys_found": "Aucune clé trouvée",
        "mod_manager": "Gestionnaire de Mods",
        "mod_manager_desc": "Gérer les Mods (LayeredFS)",
        "open_mod_folder": "Ouvrir le dossier",
        "no_mods_found": "Aucun mod trouvé",
        "mod_enabled": "Activé",
        "mod_disabled": "Désactivé",
        # Log Manager
        "log_manager": "Gestion des journaux",
        "log_manager_desc": "Gérer les journaux de l'application, les exporter pour signaler des problèmes.",
        "export_logs": "Exporter les journaux",
        "open_log_dir": "Ouvrir dossier journaux",
        "log_export_success": "Journaux exportés avec succès vers :\n{}",
        "log_export_fail": "Échec de l'exportation des journaux :\n{}",
        "toggle_mod": "Basculer",
        "on": "Marche",
        "off": "Arrêt",
        "no_build": "Aucun build",
        "log_folder_empty": "Le dossier des journaux est vide.",
        "create_folder_fail": "Impossible de créer le dossier : {}",
        "exe_not_found": "Exécutable introuvable : {}",
        "create_dir_fail": "Échec de la création du répertoire : {}\n{}",
    }
}
